server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.10.230:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: system
      __path__: /var/log/*log

- job_name: apache
  static_configs:
  - targets:
      - localhost
    labels:
      job: apache
      __path__: /var/log/apache2/*.log

